apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - protocol: TCP
      port: 9000
      targetPort: web
