apiVersion: v1
kind: Service
metadata:
  name: {{ include "users-chart.fullname" . }}
  labels:
    {{- include "users-chart.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "users-chart.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: http
      name: web
