apiVersion: batch/v1
kind: Job
metadata:
  name: users-initdb
spec:
  template:
    metadata:
      name: users-initdb
    spec:
      restartPolicy: Never
      containers:
        - name: migrate-job
          envFrom:
            - secretRef:
                name: db-uri
          image: krapoed/otus_arch:v0.1
          command:
            - python
            - src/cli.py
  backoffLimit: 2
